# Generated by Django 5.2.7 on 2025-10-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('hours', models.IntegerField(default=0)),
                ('minutes', models.IntegerField(default=50)),
                ('seconds', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=100)),
                ('uuid', models.IntegerField(default=0)),
                ('priority', models.IntegerField(default=0)),
            ],
        ),
    ]
